import type { Metadata } from "next";
import "../globals.css";
import Right_Side_Login_Page from "./Templates/right_side";
import { PhoneCall } from "lucide-react";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (

    <main className="flex">
      <div className="flex-1 bg-white min-h-screen flex flex-col px-10 max-[400px]:px-8  py-8">
        {/* Logo */}
        <div>
          <img
            src="/vantage_logo_small_screen.png"
            alt="Vantage"
            className="w-[125px]"
          />
        </div>
        {children}


        {/* Footer */}
          <div className="flex items-center justify-between max-[900px]:flex-col max-[900px]:items-start max-[900px]:gap-4 ">
            <p className="font-inter text-[15px] font-normal text-[#697E79]">
              Already have an account?{" "}
              <span className="font-semibold text-[#638125] text-[15px] cursor-pointer">
                Log in
              </span>
            </p>

            <button className="flex items-center gap-3 rounded-full bg-[#223933] px-5 py-3 text-white font-inter text-[14px] font-medium">
              <PhoneCall color="#BAE959" className="w-4.5 h-4.5" />
              Contact Support
            </button>
          </div>
      </div>


      <div className="flex-1 max-[900px]:flex-0 max-[900px]:hidden block">
        <Right_Side_Login_Page />
      </div>
    </main>


  );
}
